### ISSUE TITLE
it wont start

### ISSUE THREAD

**Issue by TobiasHG** [rodjun/python_csgo_radar#4] opened 2017-11-29 22:03 UTC
Traceback (most recent call last):
  File "C:\Users\Tobias\Desktop\python_csgo_radar-master\csgo_hack_pygame.py", line 124, in <module>
    not_a_hack = CSGORadar()
  File "C:\Users\Tobias\Desktop\python_csgo_radar-master\csgo_hack_pygame.py", line 17, in __init__
    self.config = json.loads(open("csgo/config.json", "r").read())
  File "C:\Python35\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Python35\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python35\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 7 column 3 (char 112)

running on
Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:16:59) [MSC v.1900 32 bit (Intel)] on win32
i downloaded both pygame and requests with pip

i really like you project, keep up the good work!

Tobias :)

**Comment by rodjun** [comment] 2017-11-30 01:06
Seems like your config.json might be broken, can you post it here so i can check it?

**Comment by TobiasHG** [comment] 2017-12-02 15:52
its just the default one :)

csgo/config.json https://pastebin.com/jbVKu6wZ

sorry for late reply

**Comment by TobiasHG** [comment] 2017-12-03 21:20
this works https://pastebin.com/sbiC2Cca

**Comment by rodjun** [comment] 2017-12-04 18:48
The problem is an extra "," on line 7, the last element shouldn't have it. Not sure how it was working for me lol;

**Comment by rodjun** [comment] 2017-12-04 18:50
Should be fixed now, i'll close this and when i have time I'll make some improvements to the project and release the remote radar for android and iOS.

**Closed as completed by rodjun** 2017-12-04 18:50 UTC
